version: "3"
services:
  keycloak-database:
    container_name: keycloak-database
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    volumes:
      - keycloak-database-data:/var/lib/posgresql/data/

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:12.0.4
    restart: always
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-database
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=keycloak
      - KEYCLOAK_USER=${PD_KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${PD_KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
    depends_on:
      - keycloak-database

volumes:
  keycloak-database-data:

