version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    environment:
      - PD_DOMAIN
      - PD_HTTPS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend-1
      - keycloak
    volumes:
      - dist-volume:/var/www/frontend/

  api-database:
    container_name: api-database
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=api
    volumes:
      - api-database-data:/var/lib/postgresql/data/

  backend-1:
    container_name: backend-1
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - ENV=production
      - KEYCLOAK_ADDRESS=${PD_KEYCLOAK_ADDRESS}
      - KEYCLOAK_REALM=${PD_KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${PD_KEYCLOAK_BACKEND_CLIENT_ID}
    depends_on:
      - api-database

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VUE_APP_BACKEND_ADDRESS=${PD_BACKEND_ADDRESS}
        - VUE_APP_KEYCLOAK_ADDRESS=${PD_KEYCLOAK_ADDRESS}
        - VUE_APP_KEYCLOAK_REALM=${PD_KEYCLOAK_REALM}
        - VUE_APP_KEYCLOAK_CLIENT_ID=${PD_KEYCLOAK_FRONTEND_CLIENT_ID}
    restart: on-failure
    volumes:
      - dist-volume:/frontend/dist

volumes:
  dist-volume:
  api-database-data:

