version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    environment:
      - PD_DOMAIN
      - PD_HTTPS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend-1
      - keycloak
    volumes:
      - dist-volume:/var/www/frontend/

  backend-1:
    container_name: backend-1
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 80
    restart: always
    environment:
      - KEYCLOAK_ADDRESS=${PD_KEYCLOAK_ADDRESS}
      - KEYCLOAK_REALM=${PD_KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${PD_KEYCLOAK_BACKEND_CLIENT_ID}
    depends_on:
      - api-database
      - rabbitmq
      - worker

  worker:
    container_name: worker
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: celery --app app.worker.main:app --broker amqp://rabbitmq worker --loglevel INFO
    restart: always
    depends_on:
      - rabbitmq

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VUE_APP_BACKEND_ADDRESS=${PD_BACKEND_ADDRESS}
        - VUE_APP_KEYCLOAK_ADDRESS=${PD_KEYCLOAK_ADDRESS}
        - VUE_APP_KEYCLOAK_REALM=${PD_KEYCLOAK_REALM}
        - VUE_APP_KEYCLOAK_CLIENT_ID=${PD_KEYCLOAK_FRONTEND_CLIENT_ID}
    restart: on-failure
    volumes:
      - dist-volume:/frontend/dist

volumes:
  dist-volume:

