version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    environment:
      - PD_DOMAIN
      - PD_HTTPS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend-1
      - keycloak
    volumes:
      - dist-volume:/var/www/frontend/

  backend-1:
    container_name: backend-1
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ./start_app.sh
    restart: always
    environment:
      - PD_KEYCLOAK_ADDRESS=${PD_KEYCLOAK_ADDRESS}
      - PD_KEYCLOAK_REALM=${PD_KEYCLOAK_REALM}
      - PD_KEYCLOAK_CLIENT_ID=${PD_KEYCLOAK_BACKEND_CLIENT_ID}
      - PD_CELERY_BROKER_ADDRESS=amqp://workers-broker
      - PD_CELERY_BACKEND_ADDRESS=redis://workers-backend/0
      - PD_POSTGRES_ADDRESS=api-database
      - PD_POSTGRES_USER=${PD_API_POSTGRES_USER}
      - PD_POSTGRES_PASSWORD=${PD_API_POSTGRES_PASSWORD}
      - PD_POSTGRES_DB=api
      - PD_BACKEND_HOST=0.0.0.0
      - PD_BACKEND_PORT=80
    depends_on:
      - api-database
      - workers

  workers:
    container_name: workers
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ./start_workers.sh
    restart: always
    environment:
      - PD_KEYCLOAK_ADDRESS=${PD_KEYCLOAK_ADDRESS}
      - PD_KEYCLOAK_REALM=${PD_KEYCLOAK_REALM}
      - PD_KEYCLOAK_CLIENT_ID=${PD_KEYCLOAK_BACKEND_CLIENT_ID}
      - PD_CELERY_BROKER_ADDRESS=amqp://workers-broker
      - PD_CELERY_BACKEND_ADDRESS=redis://workers-backend/0
      - PD_CELERY_LOG_LEVEL=INFO
      - PD_POSTGRES_ADDRESS=api-database
      - PD_POSTGRES_USER=${PD_API_POSTGRES_USER}
      - PD_POSTGRES_PASSWORD=${PD_API_POSTGRES_PASSWORD}
      - PD_POSTGRES_DB=api
    depends_on:
      - workers-broker
      - workers-backend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VUE_APP_BACKEND_ADDRESS=${PD_BACKEND_ADDRESS}
        - VUE_APP_KEYCLOAK_ADDRESS=${PD_KEYCLOAK_ADDRESS}
        - VUE_APP_KEYCLOAK_REALM=${PD_KEYCLOAK_REALM}
        - VUE_APP_KEYCLOAK_CLIENT_ID=${PD_KEYCLOAK_FRONTEND_CLIENT_ID}
    restart: on-failure
    volumes:
      - dist-volume:/frontend/dist

volumes:
  dist-volume:

