version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    environment:
      - PD_DOMAIN
      - PD_HTTPS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend-1
      - keycloak
    volumes:
      - dist-volume:/var/www/frontend/

  backend-1:
    container_name: backend-1
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - ENV=production

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VUE_APP_BACKEND_ADDRESS=${PD_BACKEND_ADDRESS}
        - VUE_APP_KEYCLOAK_ADDRESS=${PD_KEYCLOAK_ADDRESS}
        - VUE_APP_KEYCLOAK_REALM=${PD_KEYCLOAK_REALM}
        - VUE_APP_KEYCLOAK_CLIENT_ID=${PD_KEYCLOAK_FRONTEND_CLIENT_ID}
    restart: on-failure
    volumes:
      - dist-volume:/frontend/dist

  keycloak-database:
    container_name: keycloak-database
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    volumes:
      - keycloak-database-data:/var/lib/posgresql/data/

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:12.0.4
    restart: always
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-database
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=keycloak
      - KEYCLOAK_USER=${PD_KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${PD_KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
    depends_on:
      - keycloak-database

volumes:
  dist-volume:
  keycloak-database-data:

